feat: Add TIP 4.5
everscale-org/docs pull request #273
Opened 2022-09-08 16:54 UTC by vp-mazekine

Add support of CantBeEvil NFT licenses

2022-09-12 09:19 UTC, rualekseev commented
@vp-mazekine 

Can you change https://docs.everscale.network/standard/TIP-4 page too?

2022-09-12 09:21 UTC, rualekseev commented
@vp-mazekine 
Do we need to make func as responsible?

2022-09-12 09:30 UTC, nikitaghost commented on src/standard/TIP-4/5.md
> +interface ICantBeEvil is TIP_6 {
I think we need to remove the inheritance of TIP6

2022-09-12 09:46 UTC, ilyar requested changes
- update idex (src/standard/TIP-4/core-description.md) status `draft`
- add responsible
- squash commit
- (optional) add link implementation

2022-09-12 09:49 UTC, rualekseev commented
Implementation don't important for a draft, as i think.

2022-09-14 09:16 UTC, vp-mazekine commented
* [x] update index (src/standard/TIP-4/core-description.md) status `draft`
* [x] add responsible
* [x] squash commit

2022-09-14 09:34 UTC, vp-mazekine commented on src/standard/TIP-4/5.md
> +interface ICantBeEvil is TIP_6 {
> I think we need to remove the inheritance of TIP6

Removed inheritance

2022-09-14 14:09 UTC, closed without merging