add updated remp doc
everscale-org/docs pull request #316
Opened 2023-03-21 12:17 UTC by a-zorina

2023-03-21 13:12 UTC, eternalflow approved these changes

2023-03-22 15:04 UTC, elasticLove1 requested changes

2023-03-24 17:47 UTC, a-zorina commented on src/arch/remp.md
> +If there will be a possibility to accept it and add it to a block, then it will be done. No messages are lost — except for blockchain overloading reasons.
rephrased the paragpaph

2023-03-24 17:47 UTC, a-zorina commented on src/arch/remp.md
> +There are several checkpoints on the message processing path (when validators received the message, when message was added to a block, when the block was finalized, etc) — and depending on the messag
rephrased

2023-03-24 17:47 UTC, a-zorina commented on src/arch/remp.md
> +The validators exchange info between them using special REMP Catchain protocol. Each validator Catchain session (protocol/data structures used for controlling consensus on block candidates) is accomp
fixed

2023-03-24 17:47 UTC, a-zorina commented on src/arch/remp.md
> +This gives hard replay protection guarantees (if message has expiration mechanism included — making the message obsolete before two catchains are switched), and soft processing guarantees (message co
added replay protection section

2023-03-24 17:48 UTC, a-zorina commented on src/arch/remp.md
> +
added

2023-03-27 09:53 UTC, elasticLove1 commented on src/arch/remp.md
> +This gives hard replay protection guarantees (if message has expiration mechanism included — making the message obsolete before two catchains are switched), and soft processing guarantees (message co
Very good explanation!

2023-03-27 09:55 UTC, elasticLove1 approved these changes

2023-03-27 10:03 UTC, merged